osc=no                            # Allows for custom OSC to be used  https://github.com/cyl0/mpv-osc-morden-x
osd-bar=no                        # Вимикає панель прогресу під час перемотування.
taskbar-progress=no               # Disable playback progress rendering in taskbar
cursor-autohide=300               # Cursor hide in ms   
alang=en,eng                      # Audio language priority
slang=uk,en,eng                   # Subtitle language priority
sub-font='Netflix Sans Light'    # Specify font to use for subtitles that do not themselves specify a particular font
sub-font-size=40
sub-color='#FFFFFFFF'
sub-border-color='#FF000000'
sub-border-size=1.0
sub-shadow-offset=0
sub-spacing=0.0

sub-pos=100
secondary-sub-pos=95

# for correct work thumbfast (preview on scroll)
[Idle]
profile-cond=p["idle-active"]
profile-restore=copy-equal
title=' '
keepaspect=no
# background=1
