--password-store=basic
--ozone-platform-hint=auto
--flag-switches-begin
--enable-gpu-rasterization
--enable-zero-copy
--enable-features=CanvasOopRasterization,WebMachineLearningNeuralNetwork
--flag-switches-end
