# ~/.config/starship.toml

add_newline = false

format = "$sudo$directory$git_branch$git_status$status $character"

[sudo]
disabled = false
style =	'bold blue'
symbol = ' '
format = '[$symbol]($style)'

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold yellow)"
disabled = false

[directory]
style = "blue"
home_symbol = " "
read_only = " "
read_only_style = "red"
format = "[ $home_symbol]($style)[$read_only]($read_only_style)[$path]($style)"

[git_branch]
format = " [$symbol$branch]($style) "
symbol = " "
style = "purple"

[git_status]
style = "red"
format = '([\[$all_status$ahead_behind\]]($style))'

[status]
symbol = "  "
disabled = false
style = "bold red"
format = '[$symbol$status]($style)'
